import 'package:discover/widgets/ui/ContainerWidget.dart';
import 'package:discover/widgets/ui/LordiconWidget.dart';
import 'package:discover/widgets/ui/PageWidget.dart';
import 'package:flutter/cupertino.dart';

class AboutView extends StatelessWidget {

  const AboutView({super.key});

  @override
  Widget build(BuildContext context) {
    return PageWidget(
      title: "About DISCOver",
        body: Column(
          children: [
            LordiconWidget("star"),
            SizedBox(height: 15,),
            Text(
              "Legal Notice & License",
              style: TextStyle(fontWeight: FontWeight.w600, fontSize: 25),
              textAlign: TextAlign.center,
            ),
            SizedBox(height: 20,),
            ContainerWidget(
              Column(
                children: [
                  const Text(
                    'Application Edition',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'This music virality analysis application is provided "as is". The virality probability estimates are generated by data processing algorithms and do not constitute a guarantee of commercial success.',
                  ),
                  const SizedBox(height: 20),

                  // MIT License Section
                  const Text(
                    'Intellectual Property & License',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'The source code of this application is distributed under the MIT License.',
                  ),

                  const SizedBox(height: 8),
                  const Text(
                    'Most Icons are provided by Lordicon.com',
                  ),
                  const SizedBox(height: 12),
                  const Text(
                    'Copyright © 2026 DISCOver',
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 12),
                  const Text(
                    'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, subject to the following conditions:',
                  ),
                  const SizedBox(height: 10),
                  const Text(
                    '• The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.',
                  ),
                  const SizedBox(height: 20),

                  const Text(
                    'Disclaimer of Liability',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
                    style: TextStyle(fontSize: 12, fontStyle: FontStyle.italic),
                  ),
                ],
              )
            )
          ],
        )
    );

  }
}